trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

- script: dotnet build --configuration $(buildConfiguration) CleanArch.Utilities.sln
  displayName: 'Build solution'

- script: dotnet test CleanArch.Utilities.sln
  displayName: 'Run UTs'

- script: dotnet nuget push -s https://www.nuget.org -k $(NUGETAPIKEY) --skip-duplicate src/CleanArch.Utilities.Core/bin/Release/*.nupkg
  displayName: 'Push CleanArch.Utilities.Core to nuget.org'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: dotnet nuget push -s https://www.nuget.org -k $(NUGETAPIKEY) --skip-duplicate src/CleanArch.Utilities.DependencyInjection/bin/Release/*.nupkg
  displayName: 'Push CleanArch.Utilities.DependencyInjection to nuget.org'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: dotnet nuget push -s https://www.nuget.org -k $(NUGETAPIKEY) --skip-duplicate src/CleanArch.Utilities.AspNetCore/bin/Release/*.nupkg
  displayName: 'Push CleanArch.Utilities.AspNetCore to nuget.org'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))